project:
  type: manuscript

manuscript:
  article: index.qmd
  notebooks:
    - notebook: notebooks/visualization.qmd
      title: Visualization

execute:
  freeze: auto

format:
  html:
    toc: true
    comments:
      hypothesis: true
  jasa-pdf: default
  
